# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_id', models.IntegerField()),
                ('lng_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PathFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.TextField(max_length=65535, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('intersection', models.ManyToManyField(to='avatar_core.Intersection')),
                ('p', models.ManyToManyField(to='avatar_core.Point')),
            ],
        ),
        migrations.CreateModel(
            name='RoadNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, unique=True)),
                ('grid_lat_count', models.IntegerField(null=True)),
                ('grid_lng_count', models.IntegerField(null=True)),
                ('graph', models.CharField(max_length=10485760, null=True)),
                ('shortest_path_index', models.CharField(max_length=10485760, null=True)),
                ('grid_cells', models.ManyToManyField(to='avatar_core.GridCell')),
                ('intersections', models.ManyToManyField(to='avatar_core.Intersection')),
                ('pmax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pmax', to='avatar_core.Point')),
                ('pmin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pmin', to='avatar_core.Point')),
                ('roads', models.ManyToManyField(to='avatar_core.Road')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('t', models.DateTimeField()),
                ('speed', models.IntegerField(null=True)),
                ('angle', models.IntegerField(null=True)),
                ('occupy', models.IntegerField(null=True)),
                ('src', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('p', models.ManyToManyField(to='avatar_core.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('taxi', models.CharField(max_length=255)),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avatar_core.Path')),
                ('trace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avatar_core.Trace')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='meta',
            field=models.ManyToManyField(to='avatar_core.SampleMeta'),
        ),
        migrations.AddField(
            model_name='sample',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar_core.Point'),
        ),
        migrations.AddField(
            model_name='pathfragment',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar_core.Road'),
        ),
        migrations.AddField(
            model_name='path',
            name='road',
            field=models.ManyToManyField(to='avatar_core.PathFragment'),
        ),
        migrations.AddField(
            model_name='intersection',
            name='p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avatar_core.Point'),
        ),
        migrations.AddField(
            model_name='gridcell',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar_core.Rect'),
        ),
        migrations.AddField(
            model_name='gridcell',
            name='intersections',
            field=models.ManyToManyField(to='avatar_core.Intersection'),
        ),
        migrations.AddField(
            model_name='gridcell',
            name='roads',
            field=models.ManyToManyField(to='avatar_core.Road'),
        ),
    ]
